[package]
name = "paths"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies.jzon]
version = "0.12.5"

[dependencies.windows]
version = "0.58.0"
features = [
  "Foundation_Numerics",
  "Win32_Graphics_Direct2D",
  "Win32_Graphics_Direct2D_Common",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Direct3D_Fxc",
  "Win32_Graphics_Dxgi_Common",
  "Win32_System_LibraryLoader"
]

[dependencies.windows-strings]
version = "0.1"
