[package]
name = "paths"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]
name = "libpaths"

[dependencies.windows]
version = "0.58.0"
features = [ "Win32_System_LibraryLoader" ]

[dependencies.windows-strings]
version = "0.1"
