[package]
name = "paths_addon"
edition = "2021"


[lib]
name = "paths"
crate-type = [ "cdylib" ]


[dependencies.api]
path = "../api"

[dependencies.paths_core]
path = "../core"

[dependencies.paths_data]
path = "../data"

[dependencies.paths_renderer]
path = "../renderer"

[dependencies.paths_types]
path = "../types"

[dependencies.debounce]
version = "0.2.2"

[dependencies.egui]
workspace = true

[dependencies.windows]
version = "0.58.0"
features = [
  "Win32_Graphics_Dxgi",
  "Win32_UI_WindowsAndMessaging",
]
