[package]
name = "paths_types"
edition = "2021"


[dependencies.egui]
version = "0.29.1"
features = [
  "serde",
]

[dependencies.nalgebra]
version = "0.33.0"

[dependencies.serde]
version = "1.0"
features = [
  "derive",
]
