[package]
name = "paths_core"
edition = "2021"


[dependencies.api]
path = "../api"

[dependencies.paths_data]
path = "../data"

[dependencies.paths_types]
path = "../types"

[dependencies.egui]
workspace = true
