[package]
name = "paths_core"
edition = "2021"


[dependencies.api]
path = "../api"

[dependencies.paths_data]
path = "../data"

[dependencies.paths_types]
path = "../types"

[dependencies.egui]
version = "0.29.1"

[dependencies.log]
version = "0.4.22"

[dependencies.log_err]
version = "1.1.1"
