[package]
name = "paths_core"
edition = "2021"


[dependencies.api]
path = "../api"

[dependencies.paths_data]
path = "../data"

[dependencies.paths_types]
path = "../types"

[dependencies.debounce]
version = "0.2.2"

[dependencies.egui]
workspace = true
