name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      matrix:
        include:
          - name: Windows
            image: windows-latest
            target: x86_64-pc-windows-msvc

          - name: Linux
            image: ubuntu-latest
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          cache-workspaces: crates/addon
      - run: cargo build --target ${{ matrix.target }}
        working-directory: crates/addon
      - run: cargo build --target ${{ matrix.target }} --release
        working-directory: crates/addon
