name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      matrix:
        include:
          - name: Windows
            image: windows-latest

          # - name: Linux
          #   image: ubuntu-latest

    runs-on: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: crates/addon
      # - uses: egor-tensin/setup-mingw@v2
      - run: cargo build
        working-directory: crates/addon
      - run: cargo build --release
        working-directory: crates/addon
